apiVersion: v1
kind: Service
metadata:
  name: java-perf-web-server-service
spec:
  type: NodePort
  selector:
    app: java-perf-web-server
  ports:
    - port: 5656        # Service port
      targetPort: 5656  # Container port
      nodePort: 30080   # Optional (must be 30000â€“32767)

